<?php

declare(strict_types=1);

namespace Aybarsm\Kong\AdminApi\Plugins\Authentication\Oauth2;

use Aybarsm\Kong\AdminApi\Attributes\PluginSchema;
use Aybarsm\Kong\AdminApi\Exceptions\InvalidArgumentException;
use Aybarsm\Kong\AdminApi\Exceptions\UnexpectedResponseException;
use Aybarsm\Kong\AdminApi\Internal\Data;
use Aybarsm\Kong\AdminApi\Models\Plugin;
use Aybarsm\Kong\AdminApi\Plugins\PluginConfig;
use Override;

/**
 * Typed `config` of a `oauth2` plugin (OAuth 2.0 Authentication; doc `Authentication/oauth2.md`).
 *
 * Read it from a returned Plugin with `Oauth2Config::fromPlugin($plugin)` or `PluginRegistry::config($plugin)`.
 */
#[PluginSchema('Authentication/oauth2.md', '#/properties/config')]
final readonly class Oauth2Config implements PluginConfig
{
    /** Properties the plugin doc marks `x-encrypted`; redacted in __debugInfo(). */
    private const array ENCRYPTED = ['provisionKey'];

    /** The plugin's wire name (the doc's front-matter `url`). */
    public const string NAME = 'oauth2';

    /**
     * @param bool|null         $acceptHttpIfAlreadyTerminated Accepts HTTPs requests that have already been terminated by a proxy or load balancer. Default: `false`.
     * @param string|null       $anonymous                     An optional string (consumer UUID or username) value to use as an “anonymous” consumer if authentication fail…
     * @param string|null       $authHeaderName                The name of the header that is supposed to carry the access token. Default: `authorization`.
     * @param bool|null         $enableAuthorizationCode       An optional boolean value to enable the three-legged Authorization Code flow (RFC 6742 Section 4.1). Default: `false`.
     * @param bool|null         $enableClientCredentials       An optional boolean value to enable the Client Credentials Grant flow (RFC 6742 Section 4.4). Default: `false`.
     * @param bool|null         $enableImplicitGrant           An optional boolean value to enable the Implicit Grant flow which allows to provision a token as a result of… Default: `false`.
     * @param bool|null         $enablePasswordGrant           An optional boolean value to enable the Resource Owner Password Credentials Grant flow (RFC 6742 Section 4.3). Default: `false`.
     * @param bool|null         $globalCredentials             An optional boolean value that allows using the same OAuth credentials generated by the plugin with any other… Default: `false`.
     * @param bool|null         $hideCredentials               An optional boolean value telling the plugin to show or hide the credential from the upstream service. Default: `true`.
     * @param bool|null         $mandatoryScope                An optional boolean value telling the plugin to require at least one `scope` to be authorized by the end user. Default: `false`.
     * @param bool|null         $persistentRefreshToken        Default: `false`.
     * @param Pkce|null         $pkce                          Specifies a mode of how the Proof Key for Code Exchange (PKCE) should be handled by the plugin. Default: `lax`.
     * @param string|null       $provisionKey                  The unique key the plugin has generated when it has been added to the Service.
     * @param string|null       $realm                         When authentication fails the plugin sends `WWW-Authenticate` header with `realm` attribute value.
     * @param int|float|null    $refreshTokenTtl               Time-to-live value for data Default: `1209600`.
     * @param bool|null         $reuseRefreshToken             An optional boolean value that indicates whether an OAuth refresh token is reused when refreshing an access t… Default: `false`.
     * @param list<string>|null $scopes                        Describes an array of scope names that will be available to the end user.
     * @param int|float|null    $tokenExpiration               An optional integer value telling the plugin how many seconds a token should last, after which the client wil… Default: `7200`.
     */
    public function __construct(
        public ?bool $acceptHttpIfAlreadyTerminated = null,
        public ?string $anonymous = null,
        public ?string $authHeaderName = null,
        public ?bool $enableAuthorizationCode = null,
        public ?bool $enableClientCredentials = null,
        public ?bool $enableImplicitGrant = null,
        public ?bool $enablePasswordGrant = null,
        public ?bool $globalCredentials = null,
        public ?bool $hideCredentials = null,
        public ?bool $mandatoryScope = null,
        public ?bool $persistentRefreshToken = null,
        public ?Pkce $pkce = null,
        public ?string $provisionKey = null,
        public ?string $realm = null,
        public int|float|null $refreshTokenTtl = null,
        public ?bool $reuseRefreshToken = null,
        public ?array $scopes = null,
        public int|float|null $tokenExpiration = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    #[Override]
    public static function fromArray(array $data): static
    {
        return new self(
            acceptHttpIfAlreadyTerminated: Data::boolOrNull($data, 'accept_http_if_already_terminated'),
            anonymous: Data::stringOrNull($data, 'anonymous'),
            authHeaderName: Data::stringOrNull($data, 'auth_header_name'),
            enableAuthorizationCode: Data::boolOrNull($data, 'enable_authorization_code'),
            enableClientCredentials: Data::boolOrNull($data, 'enable_client_credentials'),
            enableImplicitGrant: Data::boolOrNull($data, 'enable_implicit_grant'),
            enablePasswordGrant: Data::boolOrNull($data, 'enable_password_grant'),
            globalCredentials: Data::boolOrNull($data, 'global_credentials'),
            hideCredentials: Data::boolOrNull($data, 'hide_credentials'),
            mandatoryScope: Data::boolOrNull($data, 'mandatory_scope'),
            persistentRefreshToken: Data::boolOrNull($data, 'persistent_refresh_token'),
            pkce: Data::enumOrNull($data, 'pkce', Pkce::class),
            provisionKey: Data::stringOrNull($data, 'provision_key'),
            realm: Data::stringOrNull($data, 'realm'),
            refreshTokenTtl: Data::numberOrNull($data, 'refresh_token_ttl'),
            reuseRefreshToken: Data::boolOrNull($data, 'reuse_refresh_token'),
            scopes: Data::stringListOrNull($data, 'scopes'),
            tokenExpiration: Data::numberOrNull($data, 'token_expiration'),
        );
    }

    /**
     * @return array<string, mixed>
     */
    #[Override]
    public function toArray(): array
    {
        return Data::withoutNulls([
            'accept_http_if_already_terminated' => $this->acceptHttpIfAlreadyTerminated,
            'anonymous' => $this->anonymous,
            'auth_header_name' => $this->authHeaderName,
            'enable_authorization_code' => $this->enableAuthorizationCode,
            'enable_client_credentials' => $this->enableClientCredentials,
            'enable_implicit_grant' => $this->enableImplicitGrant,
            'enable_password_grant' => $this->enablePasswordGrant,
            'global_credentials' => $this->globalCredentials,
            'hide_credentials' => $this->hideCredentials,
            'mandatory_scope' => $this->mandatoryScope,
            'persistent_refresh_token' => $this->persistentRefreshToken,
            'pkce' => $this->pkce?->value,
            'provision_key' => $this->provisionKey,
            'realm' => $this->realm,
            'refresh_token_ttl' => $this->refreshTokenTtl,
            'reuse_refresh_token' => $this->reuseRefreshToken,
            'scopes' => $this->scopes,
            'token_expiration' => $this->tokenExpiration,
        ]);
    }

    /**
     * Redacts `x-encrypted` values.
     *
     * @return array<string, mixed>
     */
    public function __debugInfo(): array
    {
        $values = get_object_vars($this);
        foreach (self::ENCRYPTED as $property) {
            if ($values[$property] !== null) {
                $values[$property] = '***';
            }
        }

        return $values;
    }

    /**
     * Reads the typed configuration of a `oauth2` Plugin returned by the Admin API.
     *
     * @throws InvalidArgumentException     when $plugin is not a `oauth2` plugin
     * @throws UnexpectedResponseException when its `config` does not match the plugin doc
     */
    #[Override]
    public static function fromPlugin(Plugin $plugin): static
    {
        if ($plugin->name !== self::NAME) {
            throw new InvalidArgumentException(sprintf('Expected a "%s" plugin, got "%s".', self::NAME, $plugin->name));
        }

        return self::fromArray(Data::asMap($plugin->config ?? [], 'config'));
    }
}
