<?php

declare(strict_types=1);

namespace Aybarsm\Kong\AdminApi\Plugins;

use Aybarsm\Kong\AdminApi\Exceptions\UnexpectedResponseException;
use Aybarsm\Kong\AdminApi\Models\Plugin;
use Aybarsm\Kong\AdminApi\Plugins\AI\AiPromptDecorator\AiPromptDecoratorConfig;
use Aybarsm\Kong\AdminApi\Plugins\AI\AiPromptGuard\AiPromptGuardConfig;
use Aybarsm\Kong\AdminApi\Plugins\AI\AiPromptTemplate\AiPromptTemplateConfig;
use Aybarsm\Kong\AdminApi\Plugins\AI\AiProxy\AiProxyConfig;
use Aybarsm\Kong\AdminApi\Plugins\AI\AiRequestTransformer\AiRequestTransformerConfig;
use Aybarsm\Kong\AdminApi\Plugins\AI\AiResponseTransformer\AiResponseTransformerConfig;
use Aybarsm\Kong\AdminApi\Plugins\Authentication\BasicAuth\BasicAuthConfig;
use Aybarsm\Kong\AdminApi\Plugins\Authentication\HmacAuth\HmacAuthConfig;
use Aybarsm\Kong\AdminApi\Plugins\Authentication\Jwt\JwtConfig;
use Aybarsm\Kong\AdminApi\Plugins\Authentication\KeyAuth\KeyAuthConfig;
use Aybarsm\Kong\AdminApi\Plugins\Authentication\LdapAuth\LdapAuthConfig;
use Aybarsm\Kong\AdminApi\Plugins\Authentication\Oauth2\Oauth2Config;
use Aybarsm\Kong\AdminApi\Plugins\Authentication\Session\SessionConfig;
use Aybarsm\Kong\AdminApi\Plugins\Logging\FileLog\FileLogConfig;
use Aybarsm\Kong\AdminApi\Plugins\Logging\HttpLog\HttpLogConfig;
use Aybarsm\Kong\AdminApi\Plugins\Logging\Loggly\LogglyConfig;
use Aybarsm\Kong\AdminApi\Plugins\Logging\Syslog\SyslogConfig;
use Aybarsm\Kong\AdminApi\Plugins\Logging\TcpLog\TcpLogConfig;
use Aybarsm\Kong\AdminApi\Plugins\Logging\UdpLog\UdpLogConfig;
use Aybarsm\Kong\AdminApi\Plugins\Monitoring\Datadog\DatadogConfig;
use Aybarsm\Kong\AdminApi\Plugins\Monitoring\Opentelemetry\OpentelemetryConfig;
use Aybarsm\Kong\AdminApi\Plugins\Monitoring\Prometheus\PrometheusConfig;
use Aybarsm\Kong\AdminApi\Plugins\Monitoring\Statsd\StatsdConfig;
use Aybarsm\Kong\AdminApi\Plugins\Monitoring\Zipkin\ZipkinConfig;
use Aybarsm\Kong\AdminApi\Plugins\Security\Acme\AcmeConfig;
use Aybarsm\Kong\AdminApi\Plugins\Security\BotDetection\BotDetectionConfig;
use Aybarsm\Kong\AdminApi\Plugins\Security\Cors\CorsConfig;
use Aybarsm\Kong\AdminApi\Plugins\Security\IpRestriction\IpRestrictionConfig;
use Aybarsm\Kong\AdminApi\Plugins\TrafficControl\AccessControlEnforcement\AccessControlEnforcementConfig;
use Aybarsm\Kong\AdminApi\Plugins\TrafficControl\Acl\AclConfig;
use Aybarsm\Kong\AdminApi\Plugins\TrafficControl\ProxyCache\ProxyCacheConfig;
use Aybarsm\Kong\AdminApi\Plugins\TrafficControl\RateLimiting\RateLimitingConfig;
use Aybarsm\Kong\AdminApi\Plugins\TrafficControl\Redirect\RedirectConfig;
use Aybarsm\Kong\AdminApi\Plugins\TrafficControl\RequestSizeLimiting\RequestSizeLimitingConfig;
use Aybarsm\Kong\AdminApi\Plugins\TrafficControl\RequestTermination\RequestTerminationConfig;
use Aybarsm\Kong\AdminApi\Plugins\TrafficControl\ResponseRateLimiting\ResponseRateLimitingConfig;
use Aybarsm\Kong\AdminApi\Plugins\TrafficControl\StandardWebhooks\StandardWebhooksConfig;
use Aybarsm\Kong\AdminApi\Plugins\Transformation\CorrelationId\CorrelationIdConfig;
use Aybarsm\Kong\AdminApi\Plugins\Transformation\GrpcGateway\GrpcGatewayConfig;
use Aybarsm\Kong\AdminApi\Plugins\Transformation\GrpcWeb\GrpcWebConfig;
use Aybarsm\Kong\AdminApi\Plugins\Transformation\RequestTransformer\RequestTransformerConfig;
use Aybarsm\Kong\AdminApi\Plugins\Transformation\ResponseTransformer\ResponseTransformerConfig;

/**
 * The plugins with a doc in `resources/kong-admin-api/plugins/` and typed classes in this package
 * (generated by `tools/generator/plugins.py`; blocked docs are listed in `docs/plugin-notes.md`).
 */
final readonly class PluginRegistry
{
    /** @codeCoverageIgnore Static holder; never instantiated. */
    private function __construct()
    {
    }

    /**
     * Wire name => typed config class, for every documented plugin.
     *
     * @return array<string, class-string<PluginConfig>>
     */
    public static function configs(): array
    {
        return [
            AccessControlEnforcementConfig::NAME => AccessControlEnforcementConfig::class,
            AclConfig::NAME => AclConfig::class,
            AcmeConfig::NAME => AcmeConfig::class,
            AiPromptDecoratorConfig::NAME => AiPromptDecoratorConfig::class,
            AiPromptGuardConfig::NAME => AiPromptGuardConfig::class,
            AiPromptTemplateConfig::NAME => AiPromptTemplateConfig::class,
            AiProxyConfig::NAME => AiProxyConfig::class,
            AiRequestTransformerConfig::NAME => AiRequestTransformerConfig::class,
            AiResponseTransformerConfig::NAME => AiResponseTransformerConfig::class,
            BasicAuthConfig::NAME => BasicAuthConfig::class,
            BotDetectionConfig::NAME => BotDetectionConfig::class,
            CorrelationIdConfig::NAME => CorrelationIdConfig::class,
            CorsConfig::NAME => CorsConfig::class,
            DatadogConfig::NAME => DatadogConfig::class,
            FileLogConfig::NAME => FileLogConfig::class,
            GrpcGatewayConfig::NAME => GrpcGatewayConfig::class,
            GrpcWebConfig::NAME => GrpcWebConfig::class,
            HmacAuthConfig::NAME => HmacAuthConfig::class,
            HttpLogConfig::NAME => HttpLogConfig::class,
            IpRestrictionConfig::NAME => IpRestrictionConfig::class,
            JwtConfig::NAME => JwtConfig::class,
            KeyAuthConfig::NAME => KeyAuthConfig::class,
            LdapAuthConfig::NAME => LdapAuthConfig::class,
            LogglyConfig::NAME => LogglyConfig::class,
            Oauth2Config::NAME => Oauth2Config::class,
            OpentelemetryConfig::NAME => OpentelemetryConfig::class,
            PrometheusConfig::NAME => PrometheusConfig::class,
            ProxyCacheConfig::NAME => ProxyCacheConfig::class,
            RateLimitingConfig::NAME => RateLimitingConfig::class,
            RedirectConfig::NAME => RedirectConfig::class,
            RequestSizeLimitingConfig::NAME => RequestSizeLimitingConfig::class,
            RequestTerminationConfig::NAME => RequestTerminationConfig::class,
            RequestTransformerConfig::NAME => RequestTransformerConfig::class,
            ResponseRateLimitingConfig::NAME => ResponseRateLimitingConfig::class,
            ResponseTransformerConfig::NAME => ResponseTransformerConfig::class,
            SessionConfig::NAME => SessionConfig::class,
            StandardWebhooksConfig::NAME => StandardWebhooksConfig::class,
            StatsdConfig::NAME => StatsdConfig::class,
            SyslogConfig::NAME => SyslogConfig::class,
            TcpLogConfig::NAME => TcpLogConfig::class,
            UdpLogConfig::NAME => UdpLogConfig::class,
            ZipkinConfig::NAME => ZipkinConfig::class,
        ];
    }

    /**
     * Whether $name is a documented plugin with typed classes.
     */
    public static function has(string $name): bool
    {
        return isset(self::configs()[$name]);
    }

    /**
     * The typed configuration of $plugin, or null when the plugin has no doc in this package.
     *
     * @throws UnexpectedResponseException when its `config` does not match the plugin doc
     */
    public static function config(Plugin $plugin): ?PluginConfig
    {
        $class = self::configs()[$plugin->name] ?? null;

        return $class === null ? null : $class::fromPlugin($plugin);
    }
}
